/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.Service;
import dao.ServiceDAO;
import java.util.List;
/**
 *
 * @author Asus
 */
public class ServiceForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public ServiceForm() {
        initComponents(); // <--- QUAN TRỌNG: Phải có dòng này để khởi tạo giao diện
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Hiển thị form ra giữa màn hình
        loadData(); // Tải dữ liệu từ CSDL lên bảng ngay khi mở form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        madv = new javax.swing.JLabel();
        txtmadv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttendv = new javax.swing.JTextField();
        thoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtgiatien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dịch vụ");

        madv.setText("Mã dịch vụ");

        txtmadv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmadvActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên dịch vụ");

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá tiền");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá tiền"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(madv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmadv)
                                    .addComponent(txttendv)
                                    .addComponent(txtgiatien)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(them)
                                        .addGap(75, 75, 75)
                                        .addComponent(sua)
                                        .addGap(79, 79, 79)
                                        .addComponent(xoa)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thoat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmadv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(madv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttendv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtgiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(sua)
                    .addComponent(xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(thoat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    // Hàm hỗ trợ: Tải dữ liệu từ Database lên bảng
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa hết dữ liệu cũ trên bảng
        
        ServiceDAO dao = new ServiceDAO();
        List<Service> list = dao.getAll();
        for (Service s : list) {
            model.addRow(new Object[]{ s.getMaDV(), s.getTenDV(), s.getGiaTienHienThi() });
        }
    }

    private void themActionPerformed(java.awt.event.ActionEvent evt) {                                     
    // 1. Lấy model của bảng (JTable) để thao tác dữ liệu
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    // 2. Kiểm tra dữ liệu đầu vào (không để trống)
    if (txttendv.getText().trim().isEmpty() || txtgiatien.getText().trim().isEmpty() || txtmadv.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã, Tên và Giá!");
        return;
    }

    try {
        
        // Nếu thành công, thực hiện thêm vào bảng
        // Dùng String.format("%.0f", ...) để hiển thị số nguyên, loại bỏ chữ E và số thập phân thừa
        Service sv = new Service(txtmadv.getText().trim(), txttendv.getText().trim(), Double.parseDouble(txtgiatien.getText().trim().replace(",", "")));
        
        ServiceDAO dao = new ServiceDAO();
        if (dao.insert(sv)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadData(); // Tải lại bảng từ CSDL
            // 4. Xóa trắng các ô nhập sau khi thêm thành công
            txtmadv.setText("");
            txttendv.setText("");
            txtgiatien.setText("");
            txtmadv.requestFocus();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại! Có thể trùng mã.");
        }
    } catch (NumberFormatException e) {
        // Nếu người dùng nhập sai (ví dụ nhập "abc" vào ô giá)
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: Giá tiền phải là con số!");
        txtgiatien.requestFocus(); // Đưa con trỏ chuột về lại ô giá để nhập lại
    }
    }                                    

    private void txtmadvActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {                                    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow(); // Lấy dòng đang được chọn
    
    if (selectedRow != -1) {
        String maDV = jTable1.getValueAt(selectedRow, 0).toString();
        ServiceDAO dao = new ServiceDAO();
        if (dao.delete(maDV)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
            loadData(); // Tải lại bảng
            txtmadv.setText("");
            txttendv.setText("");
            txtgiatien.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một dịch vụ để xóa!");
    }
    }                                   

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
    int row = jTable1.getSelectedRow();
    txtmadv.setText(jTable1.getValueAt(row, 0).toString());
    txttendv.setText(jTable1.getValueAt(row, 1).toString());
    txtgiatien.setText(jTable1.getValueAt(row, 2).toString());
    }                                    

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {                                    
    int row = jTable1.getSelectedRow();
    
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
        return;
    }

    // 1. Kiểm tra dữ liệu không được để trống (tránh lỗi lưu ô trống vào bảng)
    if (txttendv.getText().trim().isEmpty() || txtgiatien.getText().trim().isEmpty() || txtmadv.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }

    try {
        // 2. Format lại giá tiền cho đồng bộ (tránh lỗi hiển thị 1.0E7)
        // KHỞI TẠO ĐỐI TƯỢNG SERVICE
        Service sv = new Service(txtmadv.getText().trim(), txttendv.getText().trim(), Double.parseDouble(txtgiatien.getText().trim().replace(",", "")));
        
        ServiceDAO dao = new ServiceDAO();
        if (dao.update(sv)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thành công!");
            loadData(); // Tải lại bảng
            // 3. Xóa trắng các ô nhập liệu sau khi sửa xong
            txtmadv.setText("");
            txttendv.setText("");
            txtgiatien.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại!");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: Giá tiền không hợp lệ!");
    }
    }                                   

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {                                      
            this.dispose(); // Đóng form hiện tại
        
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel madv;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    private javax.swing.JButton thoat;
    private javax.swing.JTextField txtgiatien;
    private javax.swing.JTextField txtmadv;
    private javax.swing.JTextField txttendv;
    private javax.swing.JButton xoa;
    // End of variables declaration                   
}
